/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#d9e3f6",
        "surface-container": "#e6eeff",
        "error": "#ba1a1a",
        "surface-container-high": "#dee9fc",
        "tertiary-container": "#6b7775",
        "on-tertiary-fixed": "#121e1c",
        "on-secondary-fixed": "#002113",
        "background": "#f8f9ff",
        "on-background": "#121c2a",
        "inverse-primary": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "primary": "#0058be",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#bcc9c6",
        "on-tertiary-fixed-variant": "#3d4947",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#adc6ff",
        "on-surface": "#121c2a",
        "on-tertiary-container": "#f3fffc",
        "secondary": "#006c49",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#fefcff",
        "surface-dim": "#d0dbed",
        "tertiary-fixed": "#d8e5e2",
        "outline": "#727785",
        "on-surface-variant": "#424754",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#f8f9ff",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "secondary-container": "#6cf8bb",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#27313f",
        "on-primary-fixed-variant": "#004395",
        "tertiary": "#525e5c",
        "error-container": "#ffdad6",
        "surface-tint": "#005ac2",
        "on-primary-fixed": "#001a42",
        "outline-variant": "#c2c6d6",
        "surface-container-highest": "#d9e3f6",
        "primary-container": "#2170e4",
        "on-secondary-container": "#00714d"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "unit": "8px",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
        "container-padding-mobile": "1.25rem",
        "container-padding-desktop": "2.5rem"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"]
      },
      "fontSize": {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
